### ISSUE TITLE
default is not defined

### ISSUE THREAD

**Issue by Tethik** [AndreiRegiani/falcon-jsonify#5]
When trying to use 
```python
username = req.get_json('username', dtype=str, min=1)
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/tethik/.python-envs/auth_prototype/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/tethik/.python-envs/auth_prototype/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/tethik/.python-envs/auth_prototype/lib/python3.5/site-packages/falcon/api.py", line 227, in __call__
    responder(req, resp, **params)
  File "/home/tethik/code/internal-auth-prototype/auth/__init__.py", line 11, in on_post
    username = req.get_json('username', dtype=str, min=1)
  File "/home/tethik/code/falcon-jsonify/falcon_jsonify/__init__.py", line 34, in get_json
    if default:
```

**Comment by Tethik** [comment]
After fixing above issue, I get more issues  related to python 3.
`validate` is not defined (missing the `self`)

I fix this. Then get errors from `validate` for an undefined `unicode`. 
Fixed this by replacing `unicode` references with `six.string_types`

Sigh...

**Comment by AndreiRegiani** [comment]
Thanks @Tethik
